import React from 'react';
// Hooks generated by RTK Query from our 'movieApi.ts' file
import { useGetPopularMoviesQuery, useSearchMoviesQuery } from '../services/movieApi';
// React Router
import { useLocation } from 'react-router-dom';
// Custom component
import MovieList from '../components/MovieList';

/**
 * The 'Home' page. It handles both displaying "Popular" default initial results, 
 * as well as searching when there is a search term in the URL.
 */
const Home: React.FC = () => {
  // Read whatever search terms are placed in our URL bar by the <Navbar /> component.
  // For instance, if the URL is `http://localhost:5173/?search=Batman` 
  const location = useLocation();
  const searchParams = new URLSearchParams(location.search);
  
  // The query string ('Batman') or default to an empty string.
  const searchQuery = searchParams.get('search') || '';

  /**
   * We dispatch our two RTK Query fetchers at the identical time, 
   * BUT we use `{ skip: ... }` to automatically cancel fetching one of them
   * if it isn't relevant right now. This saves bandwidth and extra network requests!
   */
  
  // Only search Popular Movies if the user HAS NOT typed in a search box.
  const { 
    data: popularData, 
    error: popularError, 
    isLoading: popularLoading 
  } = useGetPopularMoviesQuery(1, { skip: searchQuery.length > 0 });
  
  // Only search for Specific Movies if the user HAS typed in a search box.
  const { 
    data: searchData, 
    error: searchError, 
    isLoading: searchLoading 
  } = useSearchMoviesQuery(searchQuery, { skip: searchQuery.length === 0 });

  /**
   * At this point, we need to know WHICH results and states to use in the HTML layout bellow.
   * If `searchQuery` exists we are obviously looking for searched items. 
   * Otherwise, default to our popular items list.
   */
  let isLoading = false;
  let error = null;
  let movies = null;

  if (searchQuery !== '') {
    // If the user typed a search string, display those results
    isLoading = searchLoading;
    error = searchError;
    movies = searchData?.results; 
  } else {
    // Default standard page results
    isLoading = popularLoading;
    error = popularError;
    movies = popularData?.results;
  }

  // --- Start rendering our View structure to screen ---
  return (
    <div className="container mb-5">
      
      {/* A dynamic heading title that changes based on Search string */}
      <h2 className="mb-4">
        {searchQuery !== '' ? `Search Results for "${searchQuery}"` : 'Popular Movies'}
      </h2>
      
      {/* 1. Show standard loading spinner while either call is fetching. */}
      {isLoading && (
        <div className="d-flex justify-content-center my-5">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Loading content from API...</span>
          </div>
        </div>
      )}
      
      {/* 2. Show error message if API fails, usually a bad or missing API Key. */}
      {error && (
        <div className="alert alert-danger">
          Error loading movies! Remember to add your TMDB API key inside <code>src/services/movieApi.ts</code>.
        </div>
      )}

      {/* 3. If there are properly loaded API results... render them! */}
      {movies && (
        <MovieList movies={movies} /> 
      )}
      
    </div>
  );
};

export default Home;
